# Generated by Django 6.0.1 on 2026-05-03 06:06

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0016_deliverystatus_is_notified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 sao - Rất không hài lòng'), (2, '2 sao - Không hài lòng'), (3, '3 sao - Bình thường'), (4, '4 sao - Hài lòng'), (5, '5 sao - Rất hài lòng')], default=5, verbose_name='Đánh giá sao')),
                ('comment', models.TextField(blank=True, verbose_name='Bình luận')),
                ('is_recommended', models.BooleanField(default=True, verbose_name='Có推荐 không?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_public', models.BooleanField(default=True, verbose_name='Hiển thị công khai')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_review', to='dashboard.order', verbose_name='Đơn hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đánh giá đơn hàng',
                'verbose_name_plural': 'Đánh giá đơn hàng',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=home.models.get_review_image_path, verbose_name='Ảnh đánh giá')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Tiêu đề ảnh')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.orderreview', verbose_name='Đánh giá')),
            ],
            options={
                'verbose_name': 'Ảnh đánh giá',
                'verbose_name_plural': 'Ảnh đánh giá',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung trả lời')),
                ('replied_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày trả lời')),
                ('replied_by', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người trả lời')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='home.orderreview', verbose_name='Đánh giá')),
            ],
            options={
                'verbose_name': 'Trả lời đánh giá',
                'verbose_name_plural': 'Trả lời đánh giá',
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(default=True, verbose_name='Hữu ích')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày bình chọn')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='home.orderreview', verbose_name='Đánh giá')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người bình chọn')),
            ],
            options={
                'verbose_name': 'Bình chọn hữu ích',
                'verbose_name_plural': 'Bình chọn hữu ích',
                'unique_together': {('review', 'user')},
            },
        ),
    ]
