# Generated by Django 6.0.1 on 2026-04-03 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cửa hàng')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ cửa hàng')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
            ],
            options={
                'verbose_name_plural': 'Cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ tên người nhận')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('status', models.CharField(choices=[('Pending', 'Đang chờ xử lý'), ('Processing', 'Đang chế biến'), ('Shipped', 'Đang giao hàng'), ('Delivered', 'Đã giao hàng'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20, verbose_name='Trạng thái')),
                ('total_price', models.FloatField(default=0, verbose_name='Tổng tiền')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ khách hàng')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Kinh độ khách hàng')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name_plural': 'Đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên món ăn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price', models.FloatField(verbose_name='Giá tiền')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Hình ảnh')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.FloatField(verbose_name='Giá lúc mua')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
    ]
