# Generated by Django 6.0.1 on 2026-04-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='opening_hours',
            field=models.CharField(blank=True, default='9:00 - 22:00', max_length=255, verbose_name='Giờ mở cửa'),
        ),
        migrations.AddField(
            model_name='store',
            name='warehouse_info',
            field=models.TextField(blank=True, default='', verbose_name='Thông tin quản lý kho'),
        ),
    ]
