# Generated by Django 6.0.1 on 2026-04-07 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_store_opening_hours_store_warehouse_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, verbose_name='Thông tin quản lý kho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='dashboard.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name_plural': 'Quản Lý Kho',
            },
        ),
    ]
