# Generated by Django 6.0.1 on 2026-04-07 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_store_options_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('unit', models.CharField(default='cái', max_length=50, verbose_name='Đơn vị')),
                ('min_quantity', models.IntegerField(default=10, verbose_name='Tồn kho tối thiểu')),
                ('unit_price', models.FloatField(default=0, verbose_name='Giá nhập')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='Sản phẩm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name_plural': 'Sản Phẩm Kho',
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('import', 'Nhập hàng'), ('export', 'Xuất hàng')], max_length=20, verbose_name='Loại giao dịch')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('unit_price', models.FloatField(default=0, verbose_name='Đơn giá')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Nhà cung cấp')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày giao dịch')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dashboard.warehouseitem', verbose_name='Sản phẩm kho')),
            ],
            options={
                'verbose_name_plural': 'Giao Dịch Kho',
                'ordering': ['-created_at'],
            },
        ),
    ]
