# Generated by Django 6.0.1 on 2026-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_warehouseitem_warehousetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousetransaction',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nhà cung ứng'),
        ),
    ]
