# Generated by Django 6.0.1 on 2026-04-15 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_warehousetransaction_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('import', 'Nhập hàng'), ('export', 'Xuất hàng')], max_length=20, verbose_name='Loại phiếu')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='Số phiếu')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Nhà cung ứng/Người nhận')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('total_amount', models.FloatField(default=0, verbose_name='Tổng tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('is_printed', models.BooleanField(default=False, verbose_name='Đã in')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian in')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='dashboard.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name_plural': 'Phiếu Nhập/Xuất Kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('unit_price', models.FloatField(verbose_name='Đơn giá')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.warehousebatch', verbose_name='Phiếu')),
                ('warehouse_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.warehouseitem', verbose_name='Sản phẩm kho')),
            ],
            options={
                'verbose_name_plural': 'Chi Tiết Phiếu Nhập/Xuất',
            },
        ),
    ]
