# Generated by Django 6.0.1 on 2026-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_warehousebatch_warehousebatchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousebatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần cập nhật cuối'),
        ),
    ]
