# Generated by Django 6.0.1 on 2026-04-22 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_warehousebatch_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '⭐ 1 Sao - Rất tệ'), (2, '⭐⭐ 2 Sao - Tệ'), (3, '⭐⭐⭐ 3 Sao - Bình thường'), (4, '⭐⭐⭐⭐ 4 Sao - Tốt'), (5, '⭐⭐⭐⭐⭐ 5 Sao - Rất tốt')], null=True, verbose_name='Số sao')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard.order', verbose_name='Đơn hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name_plural': 'Đánh giá Đơn hàng',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'user'), name='unique_order_review_per_user')],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '⭐ 1 Sao - Rất tệ'), (2, '⭐⭐ 2 Sao - Tệ'), (3, '⭐⭐⭐ 3 Sao - Bình thường'), (4, '⭐⭐⭐⭐ 4 Sao - Tốt'), (5, '⭐⭐⭐⭐⭐ 5 Sao - Rất tốt')], null=True, verbose_name='Số sao')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name_plural': 'Đánh giá Sản phẩm',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='unique_product_review_per_user')],
            },
        ),
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '⭐ 1 Sao - Rất tệ'), (2, '⭐⭐ 2 Sao - Tệ'), (3, '⭐⭐⭐ 3 Sao - Bình thường'), (4, '⭐⭐⭐⭐ 4 Sao - Tốt'), (5, '⭐⭐⭐⭐⭐ 5 Sao - Rất tốt')], null=True, verbose_name='Số sao')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard.store', verbose_name='Cửa hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name_plural': 'Đánh giá Cửa hàng',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('store', 'user'), name='unique_store_review_per_user')],
            },
        ),
    ]
