# Generated by Django 6.0.1 on 2026-04-29 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_orderreview_productreview_storereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài viết')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Nội dung bài viết')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Tóm tắt')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Hình ảnh nổi bật')),
                ('external_link', models.URLField(blank=True, verbose_name='Liên kết bài viết bên ngoài')),
                ('source_type', models.CharField(choices=[('manual', 'Tự viết'), ('word', 'Từ Word'), ('external', 'Từ liên kết')], default='manual', max_length=20, verbose_name='Nguồn bài viết')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('archived', 'Lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
            options={
                'verbose_name_plural': 'Bài viết trang giới thiệu',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='orderreview',
            name='unique_order_review_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='productreview',
            name='unique_product_review_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='storereview',
            name='unique_store_review_per_user',
        ),
        migrations.AddField(
            model_name='about',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả'),
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storereview',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storereview',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderReview',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.DeleteModel(
            name='StoreReview',
        ),
    ]
