# Generated by Django 6.0.1 on 2026-04-29 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_customerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thông tin khách hàng', 'verbose_name_plural': 'Thông tin khách hàng'},
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Thông báo email'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Khách hàng VIP'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP đăng nhập cuối'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='loyalty_points',
            field=models.IntegerField(default=0, verbose_name='Điểm tích lũy'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English')], default='vi', max_length=10, verbose_name='Ngôn ngữ ưu tiên'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='sms_notifications',
            field=models.BooleanField(default=False, verbose_name='Thông báo SMS'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['user'], name='dashboard_c_user_id_9a4e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['is_verified'], name='dashboard_c_is_veri_503423_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['created_at'], name='dashboard_c_created_bf2a0f_idx'),
        ),
    ]
