# Generated by Django 6.0.1 on 2026-04-30 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_customerprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Hình ảnh')),
                ('category', models.CharField(choices=[('promotion', 'Khuyến mãi'), ('event', 'Sự kiện'), ('product', 'Sản phẩm mới'), ('company', 'Tin công ty'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Danh mục')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('archived', 'Đã lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tin nổi bật')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
            ],
            options={
                'verbose_name_plural': 'Tin tức',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='dashboard_n_slug_d73407_idx'), models.Index(fields=['status'], name='dashboard_n_status_17db91_idx'), models.Index(fields=['category'], name='dashboard_n_categor_585fce_idx'), models.Index(fields=['is_featured'], name='dashboard_n_is_feat_8f13bd_idx'), models.Index(fields=['created_at'], name='dashboard_n_created_85753f_idx'), models.Index(fields=['published_at'], name='dashboard_n_publish_2fc775_idx')],
            },
        ),
    ]
