# Generated by Django 6.0.1 on 2026-05-03 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_review_reviewimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], verbose_name='Đánh giá tổng thể')),
                ('food_quality', models.IntegerField(blank=True, choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], null=True, verbose_name='Chất lượng món ăn')),
                ('service_quality', models.IntegerField(blank=True, choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], null=True, verbose_name='Chất lượng dịch vụ')),
                ('delivery_speed', models.IntegerField(blank=True, choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], null=True, verbose_name='Tốc độ giao hàng')),
                ('packaging_quality', models.IntegerField(blank=True, choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], null=True, verbose_name='Chất lượng đóng gói')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung đánh giá')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('admin_reply', models.TextField(blank=True, verbose_name='Phản hồi của cửa hàng')),
                ('admin_reply_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phản hồi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to='dashboard.order', verbose_name='Đơn hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name_plural': 'Đánh giá đơn hàng',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'user'], name='dashboard_o_order_i_145652_idx'), models.Index(fields=['status'], name='dashboard_o_status_20abb5_idx'), models.Index(fields=['overall_rating'], name='dashboard_o_overall_bdaeae_idx'), models.Index(fields=['created_at'], name='dashboard_o_created_36869c_idx')],
                'unique_together': {('order', 'user')},
            },
        ),
    ]
