# Generated by Django 6.0.1 on 2026-05-03 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_orderreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giao hàng dự kiến'),
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Biển số xe')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='Loại xe')),
                ('status', models.CharField(choices=[('available', 'Sẵn sàng'), ('busy', 'Bận'), ('offline', 'Ngoại tuyến')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Vĩ độ hiện tại')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Kinh độ hiện tại')),
                ('last_location_update', models.DateTimeField(blank=True, null=True, verbose_name='Cập nhật vị trí lần cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name_plural': 'Shipper',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ nhận hàng'), ('picked_up', 'Đã lấy hàng'), ('delivering', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('failed', 'Giao hàng thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái giao hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giao cho shipper')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian lấy hàng')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giao hàng')),
                ('pickup_notes', models.TextField(blank=True, verbose_name='Ghi chú lấy hàng')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Ghi chú giao hàng')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Lý do thất bại')),
                ('pickup_photo', models.ImageField(blank=True, null=True, upload_to='delivery/pickup/', verbose_name='Ảnh lấy hàng')),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='delivery/delivery/', verbose_name='Ảnh giao hàng')),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='delivery/signature/', verbose_name='Chữ ký khách hàng')),
                ('shipper_rating', models.IntegerField(blank=True, choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], null=True, verbose_name='Đánh giá của shipper')),
                ('shipper_notes', models.TextField(blank=True, verbose_name='Ghi chú của shipper')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='dashboard.order', verbose_name='Đơn hàng')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='dashboard.shipper', verbose_name='Shipper')),
            ],
            options={
                'verbose_name_plural': 'Trạng thái giao hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='dashboard.shipper', verbose_name='Shipper giao hàng'),
        ),
        migrations.AddIndex(
            model_name='shipper',
            index=models.Index(fields=['status', 'is_active'], name='dashboard_s_status_43bbc5_idx'),
        ),
        migrations.AddIndex(
            model_name='shipper',
            index=models.Index(fields=['license_plate'], name='dashboard_s_license_cb1b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipper',
            index=models.Index(fields=['last_location_update'], name='dashboard_s_last_lo_4ebe11_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystatus',
            index=models.Index(fields=['status', 'shipper'], name='dashboard_d_status_66a914_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystatus',
            index=models.Index(fields=['order'], name='dashboard_d_order_i_50345a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystatus',
            index=models.Index(fields=['assigned_at'], name='dashboard_d_assigne_c258dc_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystatus',
            index=models.Index(fields=['delivered_at'], name='dashboard_d_deliver_426d26_idx'),
        ),
    ]
