# Generated by Django 6.0.1 on 2026-05-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_order_delivery_notes_order_estimated_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystatus',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='Đã thông báo cho shipper'),
        ),
        migrations.AddField(
            model_name='deliverystatus',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian gửi thông báo'),
        ),
    ]
