# Generated by Django 6.0.1 on 2026-05-03 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_deliverystatus_is_notified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deliverystatus',
            name='dashboard_d_status_66a914_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliverystatus',
            name='dashboard_d_order_i_50345a_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliverystatus',
            name='dashboard_d_assigne_c258dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliverystatus',
            name='dashboard_d_deliver_426d26_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipper',
            name='dashboard_s_status_43bbc5_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipper',
            name='dashboard_s_license_cb1b2d_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipper',
            name='dashboard_s_last_lo_4ebe11_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipper',
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thông tin người dùng', 'verbose_name_plural': 'Thông tin người dùng'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_time',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Người dùng VIP'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ người dùng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ người dùng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeliveryStatus',
        ),
        migrations.DeleteModel(
            name='Shipper',
        ),
    ]
